version: "3.8"
services:
  mysql:
    container_name: fivegears-bd
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
